# Generated by Django 5.2 on 2025-04-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
