# Generated by Django 5.2 on 2025-05-04 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0002_initial'),
        ('restaurants', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custommealreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_meal_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealreview',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='mealreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='custommealreview',
            unique_together={('user', 'custom_meal')},
        ),
        migrations.AlterUniqueTogether(
            name='mealreview',
            unique_together={('user', 'meal')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together={('user', 'restaurant')},
        ),
    ]
