# Generated by Django 5.2 on 2025-04-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
